version: '3'
services:
  backend:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: hsd161203 
      DB_NAME: muscleuup
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: muscleuup
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
