name: mobile
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  auto_route: ^8.0.3
  auto_route_generator: ^8.0.0
  go_router: ^13.2.4
  provider: ^6.1.2
  animated_bottom_navigation_bar: ^1.3.3
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  modal_bottom_sheet: ^3.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  auto_route_generator:
  build_runner:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env